backend:
  name: github
  repo: elmmdo/elmmdo.github.io
  branch: main
  base_url: https://decap-oauth.elmmdo78.workers.dev
  auth_endpoint: auth

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

locale: "fa"

publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "نوشته‌ها"
    label_singular: "نوشته"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true

    fields:
      - label: "عنوان"
        name: "title"
        widget: "string"

      - label: "تاریخ انتشار"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD HH:mm:ss Z"

      - label: "خلاصه"
        name: "excerpt"
        widget: "text"
        required: false

      - label: "تصویر شاخص"
        name: "image"
        widget: "image"
        required: false

      - label: "دسته‌بندی‌ها"
        name: "categories"
        widget: "list"
        required: false
        allow_add: true

      - label: "برچسب‌ها"
        name: "tags"
        widget: "list"
        required: false
        allow_add: true

      - label: "منتشر شود؟"
        name: "published"
        widget: "boolean"
        default: true

      - label: "محتوا"
        name: "body"
        widget: "markdown"

